### PR TITLE
Amend plugin settings to use enum for global cache setting

### PR DESCRIPTION
**Pull request by maguro**
Using Java enums is more typesafe and cleaner, no quotes needed, than strings.

If it's agreed that this is the way to go, then other properties will likely need to be converted in a similar fashion.

This is a backward incompatible change and will require a major bump in the plugin's version.

### CODE REVIEW

**Comment by blindpirate** [comment]
Thank you very much for your excellent work! However, I doubt if it is necessary to introduce a new `TimeUnit`? Why don't we just use `java.util.concurrent.TimeUnit`?

As for the backward compatibility, I think a better idea is providing an overload facade, like:

```
public void globalCacheFor(int count, String timeUnit){...}

public void globalCacheFor(int count, TimeUnit timeUnit){...}
```

The usage of `String` parameter is it doesn't need to be imported explicitly in `build.gradle`, which makes things a bit easier. Your opinion of enum is brilliant, though.

**Comment by maguro** [comment]
re: Why don't we just use `java.util.concurrent.TimeUnit`?  Because `MILLISECONDS`, `MICROSECONDS`, and `NANOSECONDS` didn't seem to make sense for `globalCacheFor()`.  I'm not too worried about the overlap since this is an enum for the plugin.  Maybe `TimeUnit` should be renamed to `CacheTimeUnit`?

I like your idea about overloading `globalCacheFor()`.  Let me update the PR; I'll include changes for the other enums.

**Comment by blindpirate** [comment]
If we introduce a new `TimeUnit`, it means we need to write:

```
import com.blindpirate.github.gogradle.TimeUnit.*
```

or 

```
globalCacheFor(1, com.blindpirate.github.gogradle.TimeUnit.DAY)
```

which makes users think, "WTF, I need to take a look at the source code what these units are". 

Moreover, do you really want to forbid users to use `MILLISECONDS`, like

```
globalCacheFor(1500, TimeUnit.MILLISECONDS)
```
?

I agree with you on that these tiny units doesn't make sense in cache, but in my opinion they're implementation details, we should allow the usage and output a warning or something if necessary, WDYT?

**Comment by maguro** [comment]
There's no need for the import or package prefix for  `CacheTimeUnit` enums; there's no need for it for `BuildMode` enums.  This seems to work:

    golang {
        buildMode = DEVELOP
        packagePath = 'github.com/my/project'
        goVersion = '1.7.1'
        globalCacheFor 1, DAY
        goExecutable = '${StringUtils.toUnixString(goBinPath)}'
    }

If the tiny units don't make sense then they should not be provided.

**Comment by blindpirate** [comment]
Good catch! the `BuildMode` enum is processed with some "magic" [here](https://github.com/maguro/gogradle/blob/3d09c7300ffc9d1a191b0daf925f744eec81f099/src/main/java/com/github/blindpirate/gogradle/GolangPlugin.java#L88). The code you mentioned will result in an error:

```
* What went wrong:
A problem occurred evaluating root project 'gogs'.
> Could not get unknown property 'DAY' for object of type com.github.blindpirate.gogradle.GolangPluginSetting.
```

**Comment by maguro** [comment]
Yeah, the enums get registered in the plugin's `init()`.  I wonder how the tests for `DependencyTestWithMockGit` pass.  Could you be testing against an old plugin?

**Comment by blindpirate** [comment]
I'm sorry, I don't understand what you mean. What's up with `DependencyTestWithMockGit`?

**Comment by maguro** [comment]
The test `DependencyTestWithMockGit` uses the above code snippet in its `setup()`.  This confirms that the enums from `CacheTimeUnit`, e.g. `DAY`, are being properly registered.

**Comment by maguro** [comment]
I've also confirmed that autocomplete for `globalCacheFor` works great IntelliJ.

**Comment by maguro** [comment]
I think this PR is good to go.

**Comment by blindpirate** [comment]
I'm sorry, but I don't have time to review and verify it in weekdays. I'll take a look at it tomorrow.

**Comment by maguro** [comment]
No worries.  Thanks!

**Comment by blindpirate** [comment]
Merged, thanks!

**Pull request merged**
