### PR TITLE
Provide hook for custom test result output.

### PR DESCRIPTION
**Pull request by jonpspri**
As part of running 'gogradle' as part of an overall Travis build, I needed to be able to dump test results into the standard output stream while still taking advantage of all the other gogradle yumminess.  After putzing around for a bit, I determined that creating some sort of override in the GoTest class was the least inelegant way of solving my problem.

This pull introduces indirection for the function that passes the test results to the output generation routine, and makes the indirection available to receive a lambda function or Groovy closure.  (It occurs to me as I type this that the function should probably be a straight DSL function rather than a setter -- if others agree that should be a fairly simple change.)

### CODE REVIEW

**Comment by jonpspri** [comment]
@blindpirate, we're using this patch in the apache/incubator-openwhisk-cli build.  Could you look at it and let is know if/when it's something you'd want to integrate into the broader gogradle?

**Comment by blindpirate** [comment]
Well, my apologies for the late response. I wonder what the use case is. I'm a bit reluctant to integrate this one because `TestClassResult` is a Gradle internal API, which should not be exposed. Maybe we can discuss on the use case and try to find out a better solution.

**Comment by jonpspri** [comment]
Understandable concern.  The use case is that the ‘test’ task is being used within a Travis CI build.  The HTML representation of the results is very inconvenient for the case where the test fails because the file system is not accessible.  Instead, in true Travis fashion, we dump everything to stdout to be used later.  

I can respect not wanting to expose TestClassResult.  Perhaps a wrapper class so the internals can be hidden?  I think I only need the message String to be exposed but need to double-check.

**Comment by blindpirate** [comment]
What about https://github.com/gogradle/gogradle/pull/150?

**Comment by jonpspri** [comment]
It would get the job done.  Not great for post processing, but we don’t need that (yet).

**Comment by blindpirate** [comment]
Glad to hear that, thanks for raising this.

**Comment by jonpspri** [comment]
You’re welcome.  I’ll reopen or open a new issue if we run into further problems.  Meanwhile, I got to refresh my knowledge of Java lambdas.

**Pull request closed without merging**
